"""
AWS SES Email Service — Sends transactional emails via Amazon SES.

Supports:
- Sending plain-text and HTML emails
- Reply drafts generated by the email agent
- Notification emails (NSI alerts, task reminders)
"""

import logging
import re
import threading
from typing import Optional

import boto3

# Simple email regex for basic validation before calling SES
_EMAIL_RE = re.compile(r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$")
from botocore.exceptions import ClientError
from app.config import get_settings

settings = get_settings()
logger = logging.getLogger(__name__)


class SESService:
    """AWS SES wrapper for sending transactional emails with basic validation."""

    def __init__(self):
        self.client = boto3.client(
            "ses",
            region_name=settings.ses_region,
            aws_access_key_id=settings.aws_access_key_id or None,
            aws_secret_access_key=settings.aws_secret_access_key or None,
        )
        self.sender = settings.ses_sender_email

    def send_email(
        self,
        to: str,
        subject: str,
        body_text: str,
        body_html: Optional[str] = None,
        reply_to: Optional[str] = None,
    ) -> dict:
        """Send an email via SES.

        Args:
            to: Recipient email address (validated against a simple regex).
            subject: Email subject line.
            body_text: Plain-text body (always sent).
            body_html: Optional HTML body.
            reply_to: Optional reply-to address.

        Returns:
            Dict with SES MessageId and status on success.

        Raises:
            ValueError: If sender is unconfigured or recipient is invalid.
            ClientError: On SES API failure.
        """
        if not self.sender:
            raise ValueError("SES_SENDER_EMAIL is not configured in .env")
        if not _EMAIL_RE.match(to):
            raise ValueError(f"Invalid recipient email address: {to}")

        destination = {"ToAddresses": [to]}
        message = {
            "Subject": {"Data": subject, "Charset": "UTF-8"},
            "Body": {
                "Text": {"Data": body_text, "Charset": "UTF-8"},
            },
        }
        if body_html:
            message["Body"]["Html"] = {"Data": body_html, "Charset": "UTF-8"}

        kwargs: dict = {
            "Source": self.sender,
            "Destination": destination,
            "Message": message,
        }
        if reply_to:
            kwargs["ReplyToAddresses"] = [reply_to]

        try:
            response = self.client.send_email(**kwargs)
            message_id = response.get("MessageId", "")
            logger.info("Email sent to %s — MessageId: %s", to, message_id)
            return {"message_id": message_id, "status": "sent"}
        except ClientError as exc:
            error_code = exc.response.get("Error", {}).get("Code", "")
            logger.error("SES send failed (%s): %s", error_code, exc)
            raise

    def verify_email(self, email: str) -> dict:
        """Request SES identity verification (required in sandbox mode before sending)."""
        if not _EMAIL_RE.match(email):
            raise ValueError(f"Invalid email address: {email}")
        try:
            self.client.verify_email_identity(EmailAddress=email)
            logger.info("Verification email sent to %s", email)
            return {"email": email, "status": "verification_sent"}
        except ClientError as exc:
            logger.error("SES verify failed: %s", exc)
            raise

    def check_sending_enabled(self) -> dict:
        """Return SES account quota: max 24h send, sent last 24h, max send rate."""
        try:
            quota = self.client.get_send_quota()
            return {
                "max_24hr": quota.get("Max24HourSend", 0),
                "sent_last_24hr": quota.get("SentLast24Hours", 0),
                "max_per_second": quota.get("MaxSendRate", 0),
            }
        except ClientError as exc:
            logger.error("SES quota check failed: %s", exc)
            return {"error": str(exc)}


_ses_service: Optional[SESService] = None
_ses_lock = threading.Lock()


def get_ses_service() -> SESService:
    """Get singleton SES service (thread-safe)."""
    global _ses_service
    if _ses_service is None:
        with _ses_lock:
            if _ses_service is None:
                _ses_service = SESService()
    return _ses_service
